FROM php:7.4

RUN set -eux \
  && cd /usr/local/sbin \
  && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
  && php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" \
  && php composer-setup.php \
  && php -r "unlink('composer-setup.php');" \
  && echo 'php /usr/local/sbin/composer.phar $@' > /usr/local/sbin/composer \
  && chmod +x /usr/local/sbin/composer \
  && curl -L -o phpunit https://phar.phpunit.de/phpunit-9.phar \
  && chmod +x phpunit \
  && ./phpunit --version

CMD ["phpunit", "--bootstrap", "src/autoload.php", "tests"] 
